import type { Plant, StrateInfo } from "@/types/plant";

// Base de plantes. Objectif produit : faire grandir cette liste à 100+ espèces
// (voir BRIEF section 6 pour les sources de données à privilégier).
export const PLANTS: Plant[] = [
  { id: 1, prix: 55, nom: "Pommier", latin: "Malus domestica", emoji: "🍎", zoneMin: 3, zone: "3", indigene: false, forme: "Arbre", hauteur: [3, 5], espacement: 5, sol: ["moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Nourriture faune", "Pollinisateurs"], strate: "sous-canopee", roleGuilde: "arbre-central", orientation_preferee: "S", couleur: "#C0392B", ecologie: "Arbre fruitier central classique des guildes de permaculture. Nécessite un pollinisateur compatible à proximité. Excellente structure d'accueil pour un sous-étage productif." },
  { id: 2, prix: 58, nom: "Poirier", latin: "Pyrus communis", emoji: "🍐", zoneMin: 4, zone: "4", indigene: false, forme: "Arbre", hauteur: [4, 6], espacement: 5, sol: ["moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Nourriture faune", "Pollinisateurs"], strate: "sous-canopee", roleGuilde: "arbre-central", orientation_preferee: "S", couleur: "#B5A642", ecologie: "Fruitier robuste et longévif. Plus tolérant aux sols lourds que le pommier. Floraison précoce, bon pour les pollinisateurs." },
  { id: 3, prix: 52, nom: "Prunier", latin: "Prunus domestica", emoji: "🟣", zoneMin: 4, zone: "4", indigene: false, forme: "Arbre", hauteur: [3, 5], espacement: 4, sol: ["moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Nourriture faune", "Pollinisateurs"], strate: "sous-canopee", roleGuilde: "arbre-central", orientation_preferee: "S", couleur: "#6B3A5A", ecologie: "Fruitier productif à floraison hâtive. Attire abondamment les pollinisateurs au printemps. Certaines variétés autofertiles." },
  { id: 4, prix: 48, nom: "Cerisier", latin: "Prunus cerasus", emoji: "🍒", zoneMin: 3, zone: "3", indigene: false, forme: "Arbre", hauteur: [3, 5], espacement: 4, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Nourriture faune", "Pollinisateurs", "Ornemental"], strate: "sous-canopee", roleGuilde: "arbre-central", orientation_preferee: "S", couleur: "#D4526E", ecologie: "Cerisier acidulé rustique (griotte). Résistant au froid, floraison ornementale spectaculaire. Fruits appréciés des oiseaux." },
  { id: 5, prix: 42, nom: "Argousier", latin: "Hippophae rhamnoides", emoji: "🧡", zoneMin: 2, zone: "2", indigene: false, forme: "Arbuste", hauteur: [2, 4], espacement: 2.5, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "peu", fonctions: ["Comestible", "Fixateur d'azote", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "fixateur-azote", orientation_preferee: "S-O", couleur: "#E67E22", ecologie: "Rare fruitier fixateur d'azote ! Baies très riches en vitamine C. Extrêmement rustique et tolérant à la sécheresse. Plantes mâles et femelles nécessaires." },
  { id: 6, prix: 18, nom: "Camérisier bleu", latin: "Lonicera caerulea", emoji: "🫐", zoneMin: 2, zone: "2", indigene: true, forme: "Arbuste", hauteur: [1, 2], espacement: 2, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Nourriture faune", "Pollinisateurs"], strate: "arbustive-basse", roleGuilde: "petit-fruit", orientation_preferee: "S-E", couleur: "#4A90A4", ecologie: "Floraison très précoce (avril), essentielle pour les pollinisateurs au sortir de l'hiver. Très rustique." },
  { id: 7, prix: 35, nom: "Amélanchier du Canada", latin: "Amelanchier canadensis", emoji: "🌸", zoneMin: 3, zone: "3", indigene: true, forme: "Arbre", hauteur: [4, 6], espacement: 4, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Nourriture faune", "Ornemental", "Bande riveraine"], strate: "sous-canopee", roleGuilde: "petit-fruit", orientation_preferee: "S-E", couleur: "#E8A87C", ecologie: "Première à fleurir au printemps. Fruits (petites poires) très appréciés des oiseaux et des humains. Indigène adaptable." },
  { id: 8, prix: 16, nom: "Aronie noire", latin: "Aronia melanocarpa", emoji: "🫒", zoneMin: 3, zone: "3", indigene: true, forme: "Arbuste", hauteur: [1, 1.5], espacement: 1.5, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Nourriture faune", "Couvre-sol"], strate: "arbustive-basse", roleGuilde: "petit-fruit", orientation_preferee: "S", couleur: "#6B3A5A", ecologie: "Indigène supportant les sols pauvres. Baies très riches en antioxydants. Excellent sur les pentes." },
  { id: 9, prix: 8, nom: "Framboisier", latin: "Rubus idaeus", emoji: "🍓", zoneMin: 2, zone: "2", indigene: true, forme: "Arbuste", hauteur: [1, 2], espacement: 1, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Nourriture faune", "Couvre-sol"], strate: "arbustive-basse", roleGuilde: "petit-fruit", orientation_preferee: "S-E", couleur: "#D4526E", ecologie: "Espèce pionnière indigène. Les tiges mortes abritent les insectes solitaires. Feuilles médicinales." },
  { id: 10, prix: 20, nom: "Sureau du Canada", latin: "Sambucus canadensis", emoji: "🍇", zoneMin: 3, zone: "3", indigene: true, forme: "Arbuste", hauteur: [2, 4], espacement: 3, sol: ["moyen", "lourd"], lumiere: "plein-soleil", eau: "beaucoup", fonctions: ["Comestible", "Nourriture faune", "Médicinal", "Pollinisateurs"], strate: "arbustive-haute", roleGuilde: "petit-fruit", orientation_preferee: "N-E", couleur: "#8E44AD", ecologie: "Indigène très productif en milieux humides. Fleurs et fruits comestibles et médicinaux. Aimant à oiseaux." },
  { id: 11, prix: 12, nom: "Aulne rugueux", latin: "Alnus incana", emoji: "🌿", zoneMin: 2, zone: "2b", indigene: true, forme: "Arbre", hauteur: [8, 15], espacement: 5, sol: ["moyen", "lourd"], lumiere: "plein-soleil", eau: "beaucoup", fonctions: ["Fixateur d'azote", "Brise-vent", "Bande riveraine", "Abri faune"], strate: "canopee-basse", roleGuilde: "fixateur-azote", orientation_preferee: "N-O", couleur: "#7BA05B", ecologie: "Fixateur d'azote symbiotique indigène. Colonise les sols pauvres et humides. Parfait en bande riveraine ou brise-vent." },
  { id: 12, prix: 14, nom: "Faux indigo", latin: "Amorpha fruticosa", emoji: "💜", zoneMin: 4, zone: "3b", indigene: false, forme: "Arbuste", hauteur: [2, 3], espacement: 2, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "peu", fonctions: ["Fixateur d'azote", "Pollinisateurs", "Bande riveraine"], strate: "arbustive-haute", roleGuilde: "fixateur-azote", orientation_preferee: "S-O", couleur: "#5B4A8B", ecologie: "Fixateur d'azote tolérant à la sécheresse. Fleurs violet très mellifères." },
  { id: 13, prix: 16, nom: "Myrique baumier", latin: "Myrica gale", emoji: "🌾", zoneMin: 2, zone: "2", indigene: true, forme: "Arbuste", hauteur: [0.5, 1.5], espacement: 1.5, sol: ["moyen", "lourd"], lumiere: "plein-soleil", eau: "beaucoup", fonctions: ["Fixateur d'azote", "Bande riveraine", "Médicinal"], strate: "arbustive-basse", roleGuilde: "fixateur-azote", orientation_preferee: "N-E", couleur: "#5D8A66", ecologie: "Petit arbuste indigène fixateur d'azote des milieux humides. Feuillage aromatique. Idéal en bordure de zone mouillée." },
  { id: 14, prix: 45, nom: "Érable à sucre", latin: "Acer saccharum", emoji: "🍁", zoneMin: 4, zone: "3b", indigene: true, forme: "Arbre", hauteur: [15, 20], espacement: 10, sol: ["moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Acéricole", "Abri faune", "Coupe-vent"], strate: "canopee-haute", roleGuilde: "canopee", orientation_preferee: "N", couleur: "#C0392B", ecologie: "Espèce dominante de la forêt décidue québécoise. Canopée riche, biodiversité élevée. Acériculture." },
  { id: 15, prix: 25, nom: "Peuplier faux-tremble", latin: "Populus tremuloides", emoji: "🌳", zoneMin: 1, zone: "1", indigene: true, forme: "Arbre", hauteur: [10, 20], espacement: 6, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Abri faune", "Brise-vent", "Coupe-vent"], strate: "canopee-haute", roleGuilde: "canopee", orientation_preferee: "N-O", couleur: "#BDC3C7", ecologie: "Espèce pionnière indigène très rapide. Crée un microclimat protecteur rapidement." },
  { id: 16, prix: 3, nom: "Consoude", latin: "Symphytum officinale", emoji: "🌿", zoneMin: 3, zone: "3", indigene: false, forme: "Herbacée", hauteur: [0.6, 1.2], espacement: 0.6, sol: ["moyen", "lourd"], lumiere: "mi-ombre", eau: "moyen", fonctions: ["Accumulateur de nutriments", "Pollinisateurs", "Médicinal"], strate: "couvre-sol", roleGuilde: "accumulateur", orientation_preferee: "S", couleur: "#8E44AD", ecologie: "Accumulateur de nutriments par excellence. Racine pivotante profonde qui remonte le potassium. Feuilles utilisées comme engrais vert (paillis)." },
  { id: 17, prix: 3, nom: "Pissenlit", latin: "Taraxacum officinale", emoji: "🌼", zoneMin: 1, zone: "1", indigene: false, forme: "Herbacée", hauteur: [0.1, 0.4], espacement: 0.3, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "peu", fonctions: ["Accumulateur de nutriments", "Pollinisateurs", "Comestible", "Médicinal"], strate: "couvre-sol", roleGuilde: "accumulateur", orientation_preferee: "S", couleur: "#F39C12", ecologie: "Accumulateur de nutriments via sa racine pivotante. Première source de pollen printanier." },
  { id: 18, prix: 10, nom: "Raisin d'ours", latin: "Arctostaphylos uva-ursi", emoji: "🔴", zoneMin: 2, zone: "2", indigene: true, forme: "Arbuste", hauteur: [0.1, 0.2], espacement: 1, sol: ["léger"], lumiere: "plein-soleil", eau: "peu", fonctions: ["Couvre-sol", "Nourriture faune", "Médicinal"], strate: "couvre-sol", roleGuilde: "couvre-sol", orientation_preferee: "S", couleur: "#922B21", ecologie: "Couvre-sol persistant indigène pour sols légers acides et sites secs. Contrôle l'érosion sur pente sèche." },
  { id: 19, prix: 6, nom: "Fraisier des champs", latin: "Fragaria virginiana", emoji: "🍓", zoneMin: 2, zone: "2", indigene: true, forme: "Herbacée", hauteur: [0.1, 0.2], espacement: 0.3, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Couvre-sol", "Nourriture faune", "Pollinisateurs"], strate: "couvre-sol", roleGuilde: "couvre-sol", orientation_preferee: "S", couleur: "#E74C3C", ecologie: "Fraise sauvage indigène, couvre-sol comestible parfait sous les fruitiers. Stolons colonisateurs, petits fruits savoureux." },
  { id: 20, prix: 8, nom: "Monarde fistuleuse", latin: "Monarda fistulosa", emoji: "🌸", zoneMin: 3, zone: "3", indigene: true, forme: "Herbacée", hauteur: [0.6, 1.2], espacement: 0.4, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Pollinisateurs", "Médicinal", "Ornemental"], strate: "couvre-sol", roleGuilde: "pollinisateur", orientation_preferee: "S", couleur: "#9B59B6", ecologie: "Indigène aimant à pollinisateurs et papillons. Feuillage aromatique médicinal (thé). Fleurs mauves spectaculaires." },
  { id: 21, prix: 15, nom: "Cornouiller stolonifère", latin: "Cornus sericea", emoji: "🌾", zoneMin: 2, zone: "2", indigene: true, forme: "Arbuste", hauteur: [1.5, 3], espacement: 2, sol: ["moyen", "lourd"], lumiere: "plein-soleil", eau: "beaucoup", fonctions: ["Bande riveraine", "Nourriture faune", "Ornemental"], strate: "arbustive-haute", roleGuilde: "riveraine", orientation_preferee: "N-E", couleur: "#E74C3C", ecologie: "Excellente espèce riveraine indigène. Tiges rouges ornementales en hiver. Stabilisation des berges." },
  // Lot importé depuis "P-L Liste de Plantes Vivaces utiles en Permaculture pour le Québec".
  // prix = estimation par défaut selon la forme (à ajuster) ; indigene = false par défaut
  // (statut non vérifié individuellement, à valider avant toute mention marketing).
  { id: 22, prix: 18, nom: "Aulne crispé", latin: "Alnus viridis ssp crispa", emoji: "🌿", zoneMin: 1, zone: "1", indigene: false, forme: "Arbuste", hauteur: [3.0, 3.0], espacement: 3.0, sol: ["moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Fixateur d'azote", "Comestible", "Médicinal", "Bande riveraine", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "fixateur-azote", orientation_preferee: "S", couleur: "#7BA05B", ecologie: "Fixateur d'azote (arbuste). dont les fleurs sont comestibles. usage médicinal reconnu." },
  { id: 23, prix: 6, nom: "Astragale", latin: "Astragalus canadensis", emoji: "🌼", zoneMin: 2, zone: "2", indigene: false, forme: "Herbacée", hauteur: [0.75, 1.0], espacement: 0.35, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Fixateur d'azote", "Comestible", "Nourriture faune", "Pollinisateurs"], strate: "couvre-sol", roleGuilde: "fixateur-azote", orientation_preferee: "S", couleur: "#C9A227", ecologie: "Fixateur d'azote (plante herbacée). dont les racines sont comestibles. offre nourriture à la faune. attire une large diversité de pollinisateurs. Espèce à courte durée de vie (3-4 ans) mais qui se ressème facilement." },
  { id: 24, prix: 6, nom: "Baptisia ou Lupin indigo", latin: "Baptisia australis", emoji: "💠", zoneMin: 3, zone: "3", indigene: false, forme: "Herbacée", hauteur: [1.0, 1.0], espacement: 0.6, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Fixateur d'azote", "Pollinisateurs"], strate: "couvre-sol", roleGuilde: "fixateur-azote", orientation_preferee: "S", couleur: "#4B3F8E", ecologie: "Fixateur d'azote (plante herbacée). attire une large diversité de pollinisateurs." },
  { id: 25, prix: 18, nom: "Caraganier de sibérie", latin: "Caragana arborescens", emoji: "💛", zoneMin: 2, zone: "2", indigene: false, forme: "Arbuste", hauteur: [2.0, 2.0], espacement: 2.0, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Fixateur d'azote", "Comestible", "Nourriture faune", "Pollinisateurs", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "fixateur-azote", orientation_preferee: "S", couleur: "#E8B923", ecologie: "Fixateur d'azote (arbuste). dont les fleurs, graines sont comestibles. offre nourriture à la faune. attire une large diversité de pollinisateurs." },
  { id: 26, prix: 18, nom: "Chalef argenté", latin: "Elaeagnus commutata", emoji: "🌰", zoneMin: 2, zone: "2", indigene: false, forme: "Arbuste", hauteur: [3.0, 3.0], espacement: 2.0, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Fixateur d'azote", "Comestible", "Pollinisateurs", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "fixateur-azote", orientation_preferee: "S", couleur: "#C0C0C0", ecologie: "Fixateur d'azote (arbuste). dont les graines sont comestibles. attire une large diversité de pollinisateurs." },
  { id: 27, prix: 18, nom: "Goumi du Japon", latin: "Elaeagnus multiflora", emoji: "🟠", zoneMin: 4, zone: "4", indigene: false, forme: "Arbuste", hauteur: [1.8, 3.0], espacement: 3.0, sol: ["moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Fixateur d'azote", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "fixateur-azote", orientation_preferee: "S", couleur: "#E67E22", ecologie: "Fixateur d'azote (arbuste)." },
  { id: 28, prix: 45, nom: "Robinier Faux-Acacia", latin: "Robinia pseudoacacia", emoji: "🌳", zoneMin: 3, zone: "3", indigene: false, forme: "Arbre", hauteur: [20.0, 20.0], espacement: 10.0, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Fixateur d'azote", "Accumulateur de nutriments"], strate: "canopee-haute", roleGuilde: "fixateur-azote", orientation_preferee: "S", couleur: "#F0E68C", ecologie: "Fixateur d'azote (arbre). Croissance rapide, bois très durable, mais racines drageonnantes à surveiller." },
  { id: 29, prix: 18, nom: "Shépherdie du Canada", latin: "Shepherdia canadensis", emoji: "🔴", zoneMin: 2, zone: "2", indigene: false, forme: "Arbuste", hauteur: [1.5, 1.5], espacement: 1.0, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "peu", fonctions: ["Fixateur d'azote", "Nourriture faune", "Pollinisateurs"], strate: "arbustive-basse", roleGuilde: "fixateur-azote", orientation_preferee: "S", couleur: "#B03A2E", ecologie: "Fixateur d'azote (arbuste). offre nourriture à la faune. attire une large diversité de pollinisateurs. Les fruits contiennent de la saponine, détruite à la cuisson — consommer cuits." },
  { id: 30, prix: 18, nom: "Shépherdie argenté", latin: "Shepherdia argentea", emoji: "🟥", zoneMin: 2, zone: "2", indigene: false, forme: "Arbuste", hauteur: [4.0, 4.0], espacement: 3.0, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "peu", fonctions: ["Fixateur d'azote", "Comestible", "Nourriture faune", "Pollinisateurs", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "fixateur-azote", orientation_preferee: "S", couleur: "#C0392B", ecologie: "Fixateur d'azote (arbuste). dont les fruits sont comestibles. offre nourriture à la faune. attire une large diversité de pollinisateurs. Les fruits contiennent de la saponine, détruite à la cuisson — consommer cuits." },
  { id: 31, prix: 6, nom: "Trèfle blanc", latin: "Trifolium repens", emoji: "🍀", zoneMin: 2, zone: "2", indigene: false, forme: "Herbacée", hauteur: [0.2, 0.2], espacement: 0.25, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Fixateur d'azote", "Accumulateur de nutriments", "Comestible", "Couvre-sol", "Pollinisateurs"], strate: "couvre-sol", roleGuilde: "fixateur-azote", orientation_preferee: "S", couleur: "#7CB342", ecologie: "Fixateur d'azote (plante herbacée). dont les fleurs, feuilles, graines sont comestibles. attire une large diversité de pollinisateurs. Excellent couvre-sol mellifère, souvent utilisé en engrais vert." },
  { id: 32, prix: 45, nom: "Amélanchier glabre", latin: "Amelanchier laevis", emoji: "🌸", zoneMin: 2, zone: "2", indigene: false, forme: "Arbre", hauteur: [8.0, 8.0], espacement: 5.0, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Bande riveraine", "Nourriture faune", "Pollinisateurs", "Brise-vent"], strate: "canopee-basse", roleGuilde: "arbre-central", orientation_preferee: "S", couleur: "#E8A87C", ecologie: "Arbre. dont les fruits sont comestibles. usage médicinal reconnu. offre nourriture à la faune. attire une large diversité de pollinisateurs." },
  { id: 33, prix: 18, nom: "Amélanchier feuille d'aulne", latin: "Amelanchier alnifolia", emoji: "🫐", zoneMin: 2, zone: "2", indigene: false, forme: "Arbuste", hauteur: [4.0, 4.0], espacement: 3.0, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Bande riveraine", "Nourriture faune", "Pollinisateurs", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "petit-fruit", orientation_preferee: "S", couleur: "#7D6B91", ecologie: "Arbuste. dont les fruits sont comestibles. usage médicinal reconnu. offre nourriture à la faune. attire une large diversité de pollinisateurs." },
  { id: 34, prix: 45, nom: "Micocoulier de Virginie", latin: "Celtis occidentalis", emoji: "🌳", zoneMin: 3, zone: "3", indigene: false, forme: "Arbre", hauteur: [15.0, 15.0], espacement: 8.0, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible"], strate: "canopee-haute", roleGuilde: "canopee", orientation_preferee: "S", couleur: "#8E7A4B", ecologie: "Arbre. dont les fruits sont comestibles. Pollen allergène ; tolère bien la pollution urbaine et la sécheresse." },
  { id: 35, prix: 45, nom: "Aubépine", latin: "Crataegus sp.", emoji: "🌳", zoneMin: 3, zone: "3a", indigene: false, forme: "Arbre", hauteur: [9.0, 9.0], espacement: 9.0, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Bande riveraine", "Pollinisateurs", "Brise-vent"], strate: "canopee-basse", roleGuilde: "arbre-central", orientation_preferee: "S", couleur: "#C0392B", ecologie: "Arbre. dont les fruits sont comestibles. usage médicinal reconnu. attire des pollinisateurs spécialistes. Données basées sur l'aubépine du Canada ; bois dense apprécié en menuiserie." },
  { id: 36, prix: 45, nom: "Murier blanc", latin: "Morus alba", emoji: "🍇", zoneMin: 3, zone: "3b", indigene: false, forme: "Arbre", hauteur: [10.0, 10.0], espacement: 15.0, sol: ["moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Accumulateur de nutriments", "Comestible", "Nourriture faune"], strate: "canopee-basse", roleGuilde: "arbre-central", orientation_preferee: "S", couleur: "#4A3B7A", ecologie: "Arbre. dont les fruits sont comestibles. offre nourriture à la faune. Tolère la pollution et la sécheresse, mais racines envahissantes à surveiller." },
  { id: 37, prix: 45, nom: "Prunier rouge américain", latin: "Prunus americana", emoji: "🟣", zoneMin: 3, zone: "3b", indigene: false, forme: "Arbre", hauteur: [6.0, 6.0], espacement: 4.0, sol: ["moyen"], lumiere: "plein-soleil", eau: "beaucoup", fonctions: ["Comestible", "Médicinal", "Bande riveraine", "Pollinisateurs", "Brise-vent"], strate: "sous-canopee", roleGuilde: "arbre-central", orientation_preferee: "S", couleur: "#8E3A5A", ecologie: "Arbre. dont les fruits, graines sont comestibles. usage médicinal reconnu. attire une large diversité de pollinisateurs." },
  { id: 38, prix: 45, nom: "Cerisier à grappe", latin: "Prunus virginiana", emoji: "🍒", zoneMin: 2, zone: "2a", indigene: false, forme: "Arbre", hauteur: [6.0, 6.0], espacement: 6.0, sol: ["moyen"], lumiere: "plein-soleil", eau: "beaucoup", fonctions: ["Comestible", "Médicinal", "Bande riveraine", "Pollinisateurs", "Brise-vent"], strate: "sous-canopee", roleGuilde: "arbre-central", orientation_preferee: "S", couleur: "#5B2333", ecologie: "Arbre. dont les fruits, graines sont comestibles. usage médicinal reconnu. attire une large diversité de pollinisateurs." },
  { id: 39, prix: 18, nom: "Aronie rouge", latin: "Aronia arbutifolia", emoji: "🔴", zoneMin: 4, zone: "4", indigene: false, forme: "Arbuste", hauteur: [3.0, 3.0], espacement: 2.0, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Pollinisateurs", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "petit-fruit", orientation_preferee: "S", couleur: "#B03A2E", ecologie: "Arbuste. dont les fruits sont comestibles. usage médicinal reconnu. attire une large diversité de pollinisateurs." },
  { id: 40, prix: 18, nom: "Cornouiller mâle / sauvage", latin: "Cornus mas", emoji: "🍒", zoneMin: 4, zone: "4", indigene: false, forme: "Arbuste", hauteur: [5.0, 5.0], espacement: 5.0, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Bande riveraine", "Nourriture faune", "Pollinisateurs", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "petit-fruit", orientation_preferee: "S", couleur: "#C0392B", ecologie: "Arbuste. dont les fruits sont comestibles. usage médicinal reconnu. offre nourriture à la faune. attire des pollinisateurs spécialistes." },
  { id: 41, prix: 18, nom: "Thé des bois", latin: "Gaultheria procumbens", emoji: "🔴", zoneMin: 3, zone: "3", indigene: false, forme: "Arbuste", hauteur: [0.05, 0.05], espacement: 0.15, sol: ["moyen", "lourd"], lumiere: "mi-ombre", eau: "moyen", fonctions: ["Accumulateur de nutriments", "Comestible", "Médicinal", "Couvre-sol", "Nourriture faune", "Pollinisateurs"], strate: "arbustive-basse", roleGuilde: "petit-fruit", orientation_preferee: "S-E", couleur: "#C0392B", ecologie: "Arbuste. dont les fruits, feuilles sont comestibles. usage médicinal reconnu. offre nourriture à la faune. attire une large diversité de pollinisateurs." },
  { id: 42, prix: 18, nom: "Cerisier des sables", latin: "Prunus besseyi", emoji: "🍒", zoneMin: 3, zone: "3", indigene: false, forme: "Arbuste", hauteur: [1.2, 1.2], espacement: 1.2, sol: ["moyen"], lumiere: "plein-soleil", eau: "beaucoup", fonctions: ["Comestible", "Médicinal", "Bande riveraine", "Pollinisateurs", "Brise-vent"], strate: "arbustive-basse", roleGuilde: "petit-fruit", orientation_preferee: "S", couleur: "#5B2333", ecologie: "Arbuste. dont les fruits, graines sont comestibles. usage médicinal reconnu. attire une large diversité de pollinisateurs." },
  { id: 43, prix: 18, nom: "Sumac aromatique", latin: "Rhus aromatica", emoji: "🍁", zoneMin: 3, zone: "3", indigene: false, forme: "Arbuste", hauteur: [1.5, 1.5], espacement: 2.0, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Couvre-sol", "Pollinisateurs", "Brise-vent"], strate: "arbustive-basse", roleGuilde: "petit-fruit", orientation_preferee: "S", couleur: "#C0392B", ecologie: "Arbuste. dont les fruits sont comestibles. usage médicinal reconnu. attire une large diversité de pollinisateurs." },
  { id: 44, prix: 18, nom: "Vinaigrier", latin: "Rhus typhina", emoji: "🍁", zoneMin: 3, zone: "3a", indigene: false, forme: "Arbuste", hauteur: [5.0, 5.0], espacement: 5.0, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Bande riveraine", "Pollinisateurs", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "petit-fruit", orientation_preferee: "S", couleur: "#D2691E", ecologie: "Arbuste. dont les fruits sont comestibles. usage médicinal reconnu. attire une large diversité de pollinisateurs. La sève peut irriter la peau — porter des gants pour la taille." },
  { id: 45, prix: 18, nom: "Rosier rugueux", latin: "Rosa rugosa", emoji: "🌹", zoneMin: 3, zone: "3", indigene: false, forme: "Arbuste", hauteur: [1.5, 1.5], espacement: 1.5, sol: ["moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Bande riveraine", "Nourriture faune", "Pollinisateurs", "Brise-vent"], strate: "arbustive-basse", roleGuilde: "petit-fruit", orientation_preferee: "S", couleur: "#D4526E", ecologie: "Arbuste. dont les fleurs, fruits sont comestibles. usage médicinal reconnu. offre nourriture à la faune. attire une large diversité de pollinisateurs. Très épineux ; cynorrhodons (fruits) riches en vitamine C." },
  { id: 46, prix: 18, nom: "Ronce odorante", latin: "Rubus odoratus", emoji: "🍇", zoneMin: 4, zone: "4", indigene: false, forme: "Arbuste", hauteur: [2.0, 2.0], espacement: 1.5, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Bande riveraine", "Pollinisateurs", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "petit-fruit", orientation_preferee: "S", couleur: "#8E3A5A", ecologie: "Arbuste. dont les fruits sont comestibles. usage médicinal reconnu. attire une large diversité de pollinisateurs." },
  { id: 47, prix: 18, nom: "Viorne trilobée Pimbina", latin: "Viburnum trilobum", emoji: "🔴", zoneMin: 2, zone: "2", indigene: false, forme: "Arbuste", hauteur: [3.0, 3.0], espacement: 2.0, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Bande riveraine", "Pollinisateurs", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "petit-fruit", orientation_preferee: "S", couleur: "#C0392B", ecologie: "Arbuste. dont les fruits sont comestibles. usage médicinal reconnu. attire une large diversité de pollinisateurs." },
  { id: 48, prix: 18, nom: "Viorne Lentago", latin: "Viburnum lentago", emoji: "🫐", zoneMin: 2, zone: "2a", indigene: false, forme: "Arbuste", hauteur: [5.0, 5.0], espacement: 4.0, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Bande riveraine", "Nourriture faune", "Pollinisateurs", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "petit-fruit", orientation_preferee: "S", couleur: "#4A5B3A", ecologie: "Arbuste. dont les fruits sont comestibles. usage médicinal reconnu. offre nourriture à la faune. attire une large diversité de pollinisateurs." },
  { id: 49, prix: 18, nom: "Canneberge (grande)", latin: "Vaccinium macrocarpon", emoji: "🔴", zoneMin: 3, zone: "3", indigene: false, forme: "Arbuste", hauteur: [2.0, 2.0], espacement: 2.0, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "beaucoup", fonctions: ["Comestible", "Couvre-sol", "Pollinisateurs"], strate: "arbustive-haute", roleGuilde: "couvre-sol", orientation_preferee: "S", couleur: "#A5243D", ecologie: "Arbuste. dont les baies sont comestibles. attire une large diversité de pollinisateurs. Nécessite un sol acide et humide, typique des tourbières aménagées." },
  { id: 50, prix: 18, nom: "Airelle vigne d'Ida", latin: "Vaccinium vitis-idaea", emoji: "🔴", zoneMin: 2, zone: "2", indigene: false, forme: "Arbuste", hauteur: [0.5, 0.5], espacement: 0.5, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Couvre-sol", "Nourriture faune", "Pollinisateurs"], strate: "arbustive-basse", roleGuilde: "petit-fruit", orientation_preferee: "S", couleur: "#A5243D", ecologie: "Arbuste. dont les fruits sont comestibles. usage médicinal reconnu. offre nourriture à la faune. attire une large diversité de pollinisateurs." },
  { id: 51, prix: 6, nom: "Ciboulette", latin: "Allium schoenoprasum", emoji: "🧄", zoneMin: 2, zone: "2", indigene: false, forme: "Herbacée", hauteur: [0.15, 0.15], espacement: 0.4, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Accumulateur de nutriments", "Comestible", "Médicinal", "Couvre-sol", "Pollinisateurs"], strate: "couvre-sol", roleGuilde: "accumulateur", orientation_preferee: "S", couleur: "#9B59B6", ecologie: "Plante herbacée. dont les feuilles, bulbe sont comestibles. usage médicinal reconnu. attire une large diversité de pollinisateurs." },
  { id: 52, prix: 6, nom: "Gingemble sauvage", latin: "Asarum canadense", emoji: "🌿", zoneMin: 3, zone: "3", indigene: false, forme: "Herbacée", hauteur: [0.15, 0.15], espacement: 0.25, sol: ["léger", "moyen", "lourd"], lumiere: "mi-ombre", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Couvre-sol"], strate: "couvre-sol", roleGuilde: "couvre-sol", orientation_preferee: "S-E", couleur: "#6B4A3A", ecologie: "Plante herbacée. dont les racines sont comestibles. usage médicinal reconnu. Feuilles toxiques si consommées et parfois allergènes au toucher ; seule la racine se consomme." },
  { id: 53, prix: 6, nom: "Fraises sauvages", latin: "Fragaria vesca", emoji: "🍓", zoneMin: 3, zone: "3", indigene: false, forme: "Herbacée", hauteur: [0.2, 0.2], espacement: 0.2, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Couvre-sol", "Pollinisateurs"], strate: "couvre-sol", roleGuilde: "couvre-sol", orientation_preferee: "S", couleur: "#E74C3C", ecologie: "Plante herbacée. dont les fruits sont comestibles. usage médicinal reconnu. attire une large diversité de pollinisateurs." },
  { id: 54, prix: 6, nom: "Menthe poivrée", latin: "Mentha piperita", emoji: "🌿", zoneMin: 4, zone: "4", indigene: false, forme: "Herbacée", hauteur: [0.6, 0.6], espacement: 0.4, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Couvre-sol", "Bande riveraine"], strate: "couvre-sol", roleGuilde: "riveraine", orientation_preferee: "N-E", couleur: "#4A7A5A", ecologie: "Plante herbacée. dont les feuilles sont comestibles. usage médicinal reconnu. adapté aux sols humides et bandes riveraines." },
  { id: 55, prix: 6, nom: "Thym", latin: "Thymus vulgaris", emoji: "🌿", zoneMin: 4, zone: "4", indigene: false, forme: "Herbacée", hauteur: [0.2, 0.2], espacement: 0.3, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Couvre-sol"], strate: "couvre-sol", roleGuilde: "couvre-sol", orientation_preferee: "S", couleur: "#7A8B5A", ecologie: "Plante herbacée. dont les feuilles sont comestibles. usage médicinal reconnu." },
  { id: 56, prix: 6, nom: "Violette du Canada", latin: "Viola canadensis", emoji: "🌸", zoneMin: 4, zone: "4", indigene: false, forme: "Herbacée", hauteur: [0.14, 0.14], espacement: 0.4, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Accumulateur de nutriments", "Comestible", "Médicinal", "Couvre-sol", "Pollinisateurs"], strate: "couvre-sol", roleGuilde: "accumulateur", orientation_preferee: "S", couleur: "#F7F4EE", ecologie: "Plante herbacée. dont les fleurs, feuilles sont comestibles. usage médicinal reconnu. attire une large diversité de pollinisateurs." },
  { id: 57, prix: 6, nom: "Oseille ronde", latin: "Rumex scutatus", emoji: "🌿", zoneMin: 3, zone: "3", indigene: false, forme: "Herbacée", hauteur: [0.3, 0.3], espacement: 0.6, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Accumulateur de nutriments", "Comestible", "Médicinal", "Couvre-sol"], strate: "couvre-sol", roleGuilde: "accumulateur", orientation_preferee: "S", couleur: "#6B9E7A", ecologie: "Plante herbacée. dont les feuilles sont comestibles. usage médicinal reconnu. Riche en acide oxalique — à consommer avec modération." },
  { id: 58, prix: 6, nom: "Achillée millefeuille", latin: "Achillea millefolium", emoji: "🌼", zoneMin: 3, zone: "3", indigene: false, forme: "Herbacée", hauteur: [0.5, 0.5], espacement: 0.4, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Accumulateur de nutriments", "Médicinal", "Couvre-sol", "Pollinisateurs"], strate: "couvre-sol", roleGuilde: "accumulateur", orientation_preferee: "S", couleur: "#F7F4EE", ecologie: "Plante herbacée. usage médicinal reconnu. attire des pollinisateurs spécialistes." },
  { id: 59, prix: 18, nom: "Sauge officinale", latin: "Salvia officinalis", emoji: "🌿", zoneMin: 5, zone: "5", indigene: false, forme: "Arbuste", hauteur: [1.5, 1.5], espacement: 0.5, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "peu", fonctions: ["Comestible", "Médicinal", "Nourriture faune", "Pollinisateurs"], strate: "arbustive-basse", roleGuilde: "pollinisateur", orientation_preferee: "S", couleur: "#8B9E7A", ecologie: "Arbuste. dont les fleurs, feuilles sont comestibles. usage médicinal reconnu. offre nourriture à la faune. attire des pollinisateurs spécialistes." },
  { id: 60, prix: 45, nom: "Érable Argenté", latin: "Acer saccharinum", emoji: "🍁", zoneMin: 2, zone: "2b", indigene: false, forme: "Arbre", hauteur: [24.0, 24.0], espacement: 24.0, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Accumulateur de nutriments", "Comestible", "Bande riveraine", "Abri faune", "Pollinisateurs"], strate: "canopee-haute", roleGuilde: "canopee", orientation_preferee: "S", couleur: "#BDC3C7", ecologie: "Arbre. on peut en récolter la sève. offre abri à la faune. attire une large diversité de pollinisateurs." },
  { id: 61, prix: 18, nom: "Noisetier d'Amérique", latin: "Corylus americana", emoji: "🌰", zoneMin: 4, zone: "4a", indigene: false, forme: "Arbuste", hauteur: [3.0, 3.0], espacement: 2.0, sol: ["léger", "moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Accumulateur de nutriments", "Comestible", "Médicinal", "Bande riveraine", "Abri faune", "Pollinisateurs", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "riveraine", orientation_preferee: "N-E", couleur: "#8B6B4A", ecologie: "Arbuste. dont les graines sont comestibles. usage médicinal reconnu. adapté aux sols humides et bandes riveraines. offre abri à la faune. Pollinisation par le vent ; noisettes appréciées autant par les humains que la faune." },
  { id: 62, prix: 18, nom: "Saule Discolore", latin: "Salix discolor", emoji: "🌾", zoneMin: 2, zone: "2a", indigene: false, forme: "Arbuste", hauteur: [6.0, 6.0], espacement: 4.0, sol: ["léger", "moyen", "lourd"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Accumulateur de nutriments", "Médicinal", "Bande riveraine", "Brise-vent"], strate: "arbustive-haute", roleGuilde: "riveraine", orientation_preferee: "N-E", couleur: "#B5A642", ecologie: "Arbuste. usage médicinal reconnu. adapté aux sols humides et bandes riveraines." },
  { id: 63, prix: 45, nom: "Sorbier d'Amérique", latin: "Sorbus americana", emoji: "🌳", zoneMin: 3, zone: "3", indigene: false, forme: "Arbre", hauteur: [8.0, 8.0], espacement: 5.0, sol: ["moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Comestible", "Médicinal", "Bande riveraine", "Pollinisateurs", "Brise-vent"], strate: "canopee-basse", roleGuilde: "arbre-central", orientation_preferee: "S", couleur: "#C0392B", ecologie: "Arbre. dont les fruits sont comestibles. usage médicinal reconnu. attire une large diversité de pollinisateurs. Graines riches en acide cyanhydrique, toxiques crues — à cuire avant consommation." },
  { id: 64, prix: 6, nom: "Cornouiller du Canada - Quatre temps", latin: "Cornus canadensis", emoji: "⚪", zoneMin: 2, zone: "2", indigene: false, forme: "Herbacée", hauteur: [0.2, 0.2], espacement: 0.3, sol: ["moyen"], lumiere: "plein-soleil", eau: "moyen", fonctions: ["Couvre-sol", "Bande riveraine", "Nourriture faune", "Brise-vent"], strate: "couvre-sol", roleGuilde: "riveraine", orientation_preferee: "N-E", couleur: "#F7F4EE", ecologie: "Plante herbacée. adapté aux sols humides et bandes riveraines. offre nourriture à la faune. Petit couvre-sol indigène des sous-bois, donne du relief aux bandes riveraines." },
];

export const FN_COLORS: Record<string, string> = {
  "Fixateur d'azote": "#27AE60",
  "Accumulateur de nutriments": "#8E44AD",
  "Comestible": "#E67E22",
  "Nourriture faune": "#2980B9",
  "Pollinisateurs": "#F39C12",
  "Brise-vent": "#95A5A6",
  "Bande riveraine": "#1ABC9C",
  "Couvre-sol": "#7F8C8D",
  "Ornemental": "#E91E63",
  "Médicinal": "#9B59B6",
  "Abri faune": "#3498DB",
  "Acéricole": "#D35400",
  "Coupe-vent": "#BDC3C7",
};

export const STRATES: StrateInfo[] = [
  { id: "canopee-haute", label: "Canopée haute", h: "10–25m", c: "#1A3A2A" },
  { id: "canopee-basse", label: "Canopée basse", h: "5–10m", c: "#2D5A3D" },
  { id: "sous-canopee", label: "Sous-canopée", h: "3–6m", c: "#4A7A5A" },
  { id: "arbustive-haute", label: "Arbustive haute", h: "2–4m", c: "#6B9E7A" },
  { id: "arbustive-basse", label: "Arbustive basse", h: "0.5–2m", c: "#8B6B4A" },
  { id: "couvre-sol", label: "Couvre-sol", h: "0–0.5m", c: "#B5C9BB" },
];

/** Convertit une chaîne de zone ("3b", "4", "3d") en nombre pour comparaison. */
export function zoneToNumber(zoneStr?: string | null): number {
  if (!zoneStr) return 3;
  const match = String(zoneStr).match(/(\d+)/);
  return match ? parseInt(match[1], 10) : 3;
}

/** Filtre les plantes selon la zone du client (zoneMin de la plante <= zone client). */
export function plantsForZone(clientZone?: string | null): Plant[] {
  const z = zoneToNumber(clientZone);
  return PLANTS.filter((p) => p.zoneMin <= z);
}

export function plantByName(name: string): Plant | null {
  return PLANTS.find((p) => p.nom === name) ?? null;
}

export interface PlantSummary {
  nom: string;
  strate: Plant["strate"];
  role: Plant["roleGuilde"];
  fonctions: string[];
  sol: string[];
  lumiere: Plant["lumiere"];
  eau: Plant["eau"];
  zoneMin: number;
  indigene: boolean;
  hauteur: [number, number];
  espacement: number;
  orientation_preferee: string;
}

/** Résumé allégé des plantes disponibles pour une zone, pensé pour être envoyé à l'IA. */
export function plantSummaryForZone(clientZone?: string | null): PlantSummary[] {
  return plantsForZone(clientZone).map((p) => ({
    nom: p.nom,
    strate: p.strate,
    role: p.roleGuilde,
    fonctions: p.fonctions,
    sol: p.sol,
    lumiere: p.lumiere,
    eau: p.eau,
    zoneMin: p.zoneMin,
    indigene: p.indigene,
    hauteur: p.hauteur,
    espacement: p.espacement,
    orientation_preferee: p.orientation_preferee,
  }));
}
